/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:802947:
  appc.background(230);
} //_CODE_:window1:802947:

public void nameAdded(GTextField source, GEvent event) { //_CODE_:nameTextBox:431292:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());

  if (event == GEvent.ENTERED){
    
    personalData.userName = nameTextBox.getText(); 
    // myHistory.userName = nameAdded.getText();
    // user can save the job links they get to a file for future reference
    
  }

} //_CODE_:nameTextBox:431292:

public void salaryExpectationAdded(GTextField source, GEvent event) { //_CODE_:salaryTextBox:785569:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());

  if (event == GEvent.ENTERED){
    
    salaryExp = int (salaryTextBox.getText());       
    // myHistory.experience = experienceTextBox.getText();
    // user can save the job links they get to a file for future reference
    
  }

} //_CODE_:salaryTextBox:785569:

public void exitButtonClicked(GButton source, GEvent event) { //_CODE_:exitButton:925472:
  println("exitButton - GButton >> GEvent." + event + " @ " + millis());

  exit();

} //_CODE_:exitButton:925472:

public void saveButtonClicked(GButton source, GEvent event) { //_CODE_:saveButton:582128:
  println("saveButton - GButton >> GEvent." + event + " @ " + millis());

  personalData.saveToFile(); // intiating the save
  
} //_CODE_:saveButton:582128:

public void searchButtonClicked(GButton source, GEvent event) { //_CODE_:searchButton:840559:
  println("enterButton - GButton >> GEvent." + event + " @ " + millis());
  
  jobFilter = ""; // intializing it empty at first
  
  // Adzuna API, need to cite  it  
  // storing api url in string got from adzuna
  
  String url = "https://api.adzuna.com/v1/api/jobs/ca/search/1?app_id=" + "7781b5b6" + "&app_key=" + "e2e06d46e21490095586c47b2cb7f36e" + "&what=" + "computer%20science" + "&where=Kitchener" + "&sort_by=salary" + "&salary_min=" + salaryExp;
  
  if (partTimeCheckBox.isSelected() && !fullTimeCheckBox.isSelected()){
    jobFilter += "part_time";
  }
  
  else if (fullTimeCheckBox.isSelected() && !partTimeCheckBox.isSelected()){
    jobFilter += "full_time";
  }
  
  else{
    jobFilter = "";
  }
  
  if (!jobFilter.isEmpty()){
    // only use jobFilter if its not empty
    url += "&" + jobFilter + "=1&content-type=" +"application/json";
  }
  
  else{
    url += "&content-type=" +"application/json";
  }

   // calls api/makes http request to get JSON response 
   output = loadJSONObject(url);
   jobs = output.getJSONArray("results"); //pulls the jobs and stores in array jobs
   
   personalData = new myJobs(personalData.userName); // creating myJobs with users name
   personalData.collectionOfData(jobs); // getting data from api then fillinng it into method
   
   println(url);
   beganSearch = true;
   
} //_CODE_:searchButton:840559:

public void partTimeClicked(GCheckbox source, GEvent event) { //_CODE_:partTimeCheckBox:333037:
  println("checkbox1 - GCheckbox >> GEvent." + event + " @ " + millis());

} //_CODE_:partTimeCheckBox:333037:

public void fullTimeClicked(GCheckbox source, GEvent event) { //_CODE_:fullTimeCheckBox:455418:
  println("checkbox5 - GCheckbox >> GEvent." + event + " @ " + millis());

} //_CODE_:fullTimeCheckBox:455418:

public void restartButtonClicked(GButton source, GEvent event) { //_CODE_:restartButton:421216:
  println("restartButton - GButton >> GEvent." + event + " @ " + millis());

  //clearing all text fields
  nameTextBox.setText(""); // setting text to be empty
  salaryTextBox.setText("");
  
  // deselecting all checkboxes
  partTimeCheckBox.setSelected(false);
  fullTimeCheckBox.setSelected(false);

  // resetting job Data
  personalData.jobData = new String[0]; // array's empty now
  personalData.userName = ""; // no username now
  
  //resetting boolean
  beganSearch = false;

} //_CODE_:restartButton:421216:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 450, 500, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  ynLabel = new GLabel(window1, 3, 16, 146, 68);
  ynLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  ynLabel.setText("Your Name                                Press Enter To Proceed");
  ynLabel.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  ynLabel.setOpaque(false);
  nameTextBox = new GTextField(window1, 173, 19, 152, 48, G4P.SCROLLBARS_NONE);
  nameTextBox.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  nameTextBox.setOpaque(true);
  nameTextBox.addEventHandler(this, "nameAdded");
  togGroup1 = new GToggleGroup();
  salaryLabel = new GLabel(window1, 2, 94, 154, 59);
  salaryLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  salaryLabel.setText("Salary Expectation               Press Enter To Proceed");
  salaryLabel.setOpaque(false);
  salaryTextBox = new GTextField(window1, 174, 92, 152, 47, G4P.SCROLLBARS_NONE);
  salaryTextBox.setOpaque(true);
  salaryTextBox.addEventHandler(this, "salaryExpectationAdded");
  avalabilityPrefrence = new GLabel(window1, 10, 170, 121, 48);
  avalabilityPrefrence.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  avalabilityPrefrence.setText("Availability Prefrence");
  avalabilityPrefrence.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  avalabilityPrefrence.setOpaque(false);
  exitButton = new GButton(window1, 9, 250, 94, 57);
  exitButton.setText("Exit");
  exitButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  exitButton.addEventHandler(this, "exitButtonClicked");
  saveButton = new GButton(window1, 11, 338, 92, 54);
  saveButton.setText("Save Response");
  saveButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  saveButton.addEventHandler(this, "saveButtonClicked");
  searchButton = new GButton(window1, 169, 247, 90, 60);
  searchButton.setText("Search");
  searchButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  searchButton.addEventHandler(this, "searchButtonClicked");
  partTimeCheckBox = new GCheckbox(window1, 163, 171, 120, 20);
  partTimeCheckBox.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  partTimeCheckBox.setText("Part-Time");
  partTimeCheckBox.setLocalColorScheme(GCScheme.RED_SCHEME);
  partTimeCheckBox.setOpaque(false);
  partTimeCheckBox.addEventHandler(this, "partTimeClicked");
  fullTimeCheckBox = new GCheckbox(window1, 318, 168, 120, 20);
  fullTimeCheckBox.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  fullTimeCheckBox.setText("Full-Time");
  fullTimeCheckBox.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  fullTimeCheckBox.setOpaque(false);
  fullTimeCheckBox.addEventHandler(this, "fullTimeClicked");
  restartButton = new GButton(window1, 171, 338, 90, 52);
  restartButton.setText("Restart");
  restartButton.addEventHandler(this, "restartButtonClicked");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GLabel ynLabel; 
GTextField nameTextBox; 
GToggleGroup togGroup1; 
GLabel salaryLabel; 
GTextField salaryTextBox; 
GLabel avalabilityPrefrence; 
GButton exitButton; 
GButton saveButton; 
GButton searchButton; 
GCheckbox partTimeCheckBox; 
GCheckbox fullTimeCheckBox; 
GButton restartButton; 
